# Configurations
title:            Hollis Note Sharing
description:      Be Happy

kramdown:
  math_engine: mathjax
  
#  defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "default"


# remote_theme: HollisChen/jekyll-gitbook
