# Configurations
title:            Hollis Note Sharing
description:      Be Happy

# plugins:
#   - jekyll-spaceship

# kramdown:
#   input: GFM
#   math_engine: mathjax
#   mathjax:
#     input: TeX
#     output: HTML-CSS
  
#  defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "default"


# remote_theme: HollisChen/jekyll-gitbook
